### ISSUE TITLE
meta-ci: ensure windows support

### ISSUE THREAD

**Issue by MartinBernstorff** [MartinBernstorff/swift-python-cookiecutter#109]
* Add `windows` to meta-ci
* Fix whatever breaks

I'm pretty sure I have a call to `find` somewhere in there, so something will break. Won't get it on immediately.

@KennethEnevoldsen

**Comment by KennethEnevoldsen** [comment]
Def agree (Mac really has an advantage in being similar to Linux in many ways)

**Comment by KennethEnevoldsen** [comment]
Can't find a `find` in the CI so it might be a easy fix - added it in #117

**Comment by MartinBernstorff** [comment]
Yeah, `find` was in the `.rej` checking, I replaced it with pure python 👍
