### ISSUE TITLE
ci: warn if not in a virtual environment

### ISSUE THREAD

**Issue by MartinBernstorff** [MartinBernstorff/swift-python-cookiecutter#110]
I sometimes forget to activate the .venv. Would be nice to have that automated!

Perhaps only when running `inv install`, `inv test`, `inv mypy` and `inv pr`. 

What do you think @KennethEnevoldsen?

**Comment by KennethEnevoldsen** [comment]
A warning for not being in a virtual environment is fine with me.

However, I would add a toggle constant in the tasks.py to turn it off. (e.g. when working on ucloud it would be nice not to have it all the time)

**Comment by MartinBernstorff** [comment]
Good point! I was considering that we'd probably want some project-dependent config options, putting it in `tasks.py` is a great solution to that.

**Comment by KennethEnevoldsen** [comment]
You could also have it read it from the pyproject.toml if you we want to keep all project configs in ONE place?

**Comment by MartinBernstorff** [comment]
Agreed, that's an even better suggestion 👍

**Comment by KennethEnevoldsen** [comment]
Note on this -  I am unsure whether it is possible to check. I did some experiments inspired by this (see discussion on Slack).

**Comment by MartinBernstorff** [comment]
Yeah, if each `c.run` starts a new shell, it might be. Maybe there's something in the `invoke` `Context` object, looking at Slack now.
