### ISSUE TITLE
ci: use pyright instead of mypy

### ISSUE THREAD

**Issue by MartinBernstorff** [MartinBernstorff/swift-python-cookiecutter#111]
* Ships with VSCode, so doesn't need you to install `mypy` to work.
	* `mypy` does ship with VSCode, but only lints within a given file - i.e. if an import changes its signature, you need to reload VSCode to get the update.

* Type checks unannotated code by default
	* Allows redefinition of variable types by default, and infers the variable type as the union of assigned types
	* Differentiates between explicit `Any` and implicit `Unknown`.

* Better inference:
	* Infers return types, instead of assuming `Any`. This is huge.
	* Makes a union instead of a join when merging two sets of type hints. This leads to way fewer false negatives.
	* Better type guarding

* Allows quick generation of stubs for imports in VSCode, so you can type hint the interfaces your package consumes

More detail [here](https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md).

I've been using it in VSCode instead of mypy for a while now, and I **much** prefer it. Would love to align the CI with my editor. What do you think @KennethEnevoldsen?

**Comment by KennethEnevoldsen** [comment]
I will test it out for a while and see how I like it

**Comment by KennethEnevoldsen** [comment]
My first experience is not great though. Had no idea how to parse this error, google didn't help. ChatGPT solved it though. I will try it on for a while to kinda see how it compares to mypy.
![Screenshot 2023-04-13 at 12 31 23](https://user-images.githubusercontent.com/23721977/231864270-6f6665c6-f4a9-4c29-be6c-893529f9ac54.png)
![Screenshot 2023-04-13 at 12 31 23](https://user-images.githubusercontent.com/23721977/231864659-c90d423d-19fa-4048-b8e2-75b49bc4de64.png)

**Comment by KennethEnevoldsen** [comment]
(I def. think mypy is annoying sometimes so it might be the better solution).

**Comment by MartinBernstorff** [comment]
Yeah, the errors from `pyright` take a little while to learn how to parse because they're so verbose. 

And because they distinguish between `Any` (type-hinted as `Any`) and `Unknown` (not type hinted and unable to infer). I think that's desirable behaviour, though :tu

**Comment by MartinBernstorff** [comment]
Sarah/Signe are having issues with `mypy` on Ovartaci, so further arguments for migrating to pyright. How are you finding it? :-)

**Comment by KennethEnevoldsen** [comment]
Jamen har brugt det lidt tid, det virker meget fornuftig synes jeg. Jeg er klar på et skift
