### ISSUE TITLE
pre-commit task

### ISSUE THREAD

**Issue by KennethEnevoldsen** [MartinBernstorff/swift-python-cookiecutter#92]
Hi @MartinBernstorff, I would love to ask for a pre-commit task. But the current one seems quite picky about me having commit my changes. Is it possible to remove this?

**Comment by KennethEnevoldsen** [comment]
> I love that it auto-commits changes currently, and would strongly prefer to keep that functionality.

That is why I want to use it ;) 

I would probably do
```
pre-commit -a/--auto-fix # only autofix if flag
```
Similar with docs I almost always do docs -v but it is probably not an ideal default

I don't think Lint should commit anything to a PR though, that is not something I would expect would happen if I lint (I just want it to run all the linting) - but I welcome a good counterargument.

**Comment by MartinBernstorff** [comment]
Good point! It's a trade-off between my desired workflow and conservative defaults.

Perhaps we could also do `inv pr -a` to autofix if flag? I'd be game fo rthat 👍

**Comment by KennethEnevoldsen** [comment]
works for me

**Comment by MartinBernstorff** [comment]
Great! Was basically created in #106, feel free to update if you feel anything is missing. Closing now.

**Comment by KennethEnevoldsen** [comment]
I will update it when I run into it again.
