### ISSUE TITLE
no typeguard in test in task.py?

### ISSUE THREAD

**Issue by KennethEnevoldsen** [MartinBernstorff/swift-python-cookiecutter#94]
There seems to be `no typeguard` in our pytest ci? Is that intentional?

**Comment by KennethEnevoldsen** [comment]
@MartinBernstorff

**Comment by KennethEnevoldsen** [comment]
Have never had it tell me anything actually. We should probably just remove it?

**Comment by MartinBernstorff** [comment]
Agreed 👍
