### ISSUE TITLE
meta-ci: create cruft repo with defaults and install to test that everything works

### ISSUE THREAD

**Issue by MartinBernstorff** [MartinBernstorff/swift-python-cookiecutter#97]
We've had a few breaking changes recently, perhaps it makes sense for `swift-python-cookiecutter` to have a CI step that `cruft create`s based on the template, and tries to install it?

This would check that:
* The cookiecutter template is correctly specified
* The `.toml` file etc. correctly installs

@KennethEnevoldsen, what do you think?

**Comment by KennethEnevoldsen** [comment]
Yep, def. had the same though very annoying to not have any feedback

**Comment by KennethEnevoldsen** [comment]
So basically:

- cruft create from the pr (using all defaults)
- run a series of the invoke commands
  - install
  - docs
  - lint (potientially)
- you could even have a "update an existing repo" workflow, but I don't think we need that for now.

**Comment by MartinBernstorff** [comment]
Yep, strongly agreed! The dag would be:
> a. cruft create from the pr using defaults -> 
>    b. install and
>    c. docs and
>    d. lint (definitely)

Or, potentially cruft create is so fast we don't have to couple them 👍 

I'll leave this up for now and focus on getting t2d finished, but assigning this high priority.

**Comment by KennethEnevoldsen** [comment]
Def. agree. I am working on projects here, but it would be nice to get this done

**Comment by KennethEnevoldsen** [comment]
saw. Looks great! Thanks for getting on it so fast!
