### ISSUE TITLE
ci: add codecov?

### ISSUE THREAD

**Issue by MartinBernstorff** [MartinBernstorff/swift-python-cookiecutter#99]
For projects that are public and open source, `codecov` handles coverage deltas splendidly. I think I'd be in favor of adding that as a default?

**Comment by KennethEnevoldsen** [comment]
Hmm, I am a bit hesitant here. Generally, I would like everything to be as minimal as possible to set up. This would require an extra step (which you can always add to a repo, but I think it is a poor default).

Have you tried codecov for a project?

**Comment by MartinBernstorff** [comment]
I agree! I've just touched upon a similar concern in #104.

Haven't used codecov for a project, but this might be a good reason to do so soon.

For now, maybe we should just disable the `report-only-changed-files` in `tests.yml`?

**Comment by MartinBernstorff** [comment]
Just want to point to this beautiful codecov report: https://github.com/cruft/cruft/pull/233#issuecomment-1414023468

I might very well add codecov to some of our open source projects in the future 👍

**Comment by KennethEnevoldsen** [comment]
Looks great - is also easy to add. Just don't think it should be the default.
